[tool.ruff]
# Add more rule codes as needed
extend-select = [
    "D",    # pydocstyle - to replace docformatter
]

# Ignore specific rules
lint.ignore = [
    "E731",  # Do not assign a lambda expression, use a def
    # "W503",  # Line break before binary operator - seems this has been removed in v0.3.7
    "E741",  # Do not use variables named 'l', 'O', or 'I'
    "E203",  # Whitespace before ':'
    "E266",  # Too many leading '#' for block comment
    "E501",  # Line too long (TODO: remove this once code has been refactored for other things)
    "W605",  # Invalid escape sequence
    "F401",  # Ignore unused imports in __init__.py

    # Docstring Rules to Ignore
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    "D106",  # Missing docstring in public nested class
    "D107",  # Missing docstring in __init__
    "D205",  # 1 Blank line required between summary line and description
    "D417",  # Missing argument description
]

# Exclude specific files and patterns
exclude = [
    "setup.py",
    "tests/*",
    "^.*https?://.*$",  # Long URLs in comments
    "^.*figure.*$",
]

# Set the maximum line length
line-length = 100

# Enable the count of violations
output-format = "full"

[tool.ruff.isort]
force-wrap-aliases = true
combine-as-imports = true
force-sort-within-sections = true
known-first-party = []
known-third-party = []
known-local-folder = []
lines-after-imports = 2

[tool.ruff.pydocstyle]
convention = "google"
